# default -- https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml

# ouch
[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

# relative motions
[[manager.prepend_keymap]]
on = ["m"]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

# find
[[manager.prepend_keymap]]
on = ["f", "g"]
run = "plugin fg"
desc = "find file by content (fuzzy match)"
[[manager.prepend_keymap]]
on = ["f", "G"]
run = "plugin fg -- rg"
desc = "find file by content (ripgrep match)"
[[manager.prepend_keymap]]
on = ["f", "f"]
run = "plugin fg -- fzf"
desc = "find file by filename"

# rename
[[manager.prepend_keymap]]
on = ["r", "r"]
run = "rename --cursor=before_ext"
desc = "Rename selected file(s)"
