[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_translit = false
show_hidden = true
linemode = "size"

[preview]
wrap = "yes"
max_width = 600
max_height = 900
